the variance computations in the benchmark suite weren't correctly checking for a negative average error causing a negative variance causing a computation of a sqrt against that negative causing the suite to catch and output the error as:
ERROR: square root of negative numbers is only in your imagination
awk: division by zero
 input record number 1, file
 source line number 1
/usr/brlcad/bin/benchmark: line 704: test: -le: unary operator expected

problem solved by taking the absolute value of the negative error when
computing the variance.


git-svn-id: https://svn.code.sf.net/p/brlcad/code/brlcad/trunk@25899 2f96ce8b-6d43-0410-b8df-bffccc660ffb